spring.application.name=portfolio-aggregator
server.port=8081
spring.threads.virtual.enabled=true

resilience4j.circuitbreaker.instances.customerService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.customerService.slidingWindowSize= 10
resilience4j.circuitbreaker.instances.customerService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.customerService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.customerService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.customerService.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.accountService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.accountService.slidingWindowSize= 10
resilience4j.circuitbreaker.instances.accountService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.accountService.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.investmentService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.investmentService.slidingWindowSize= 10
resilience4j.circuitbreaker.instances.investmentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.investmentService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.investmentService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.investmentService.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.riskService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.riskService.slidingWindowSize= 10
resilience4j.circuitbreaker.instances.riskService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.riskService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.riskService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.riskService.automaticTransitionFromOpenToHalfOpenEnabled=true

#Services Timepouts
portfolio.service.timeout=2000

#RestClient Timeouts
portfolio.rest.client.connect.timeout=2000
portfolio.rest.client.read.timeout=1000